import Head from 'next/head'
import Image from 'next/image'
import Depertment from '../components/Depertment'
import Navbar from '../components/navbar'
import doctors from '../components/images/doctors.png'
import palyBtn from '../components/images/icon/play-btn.png'
export default function Home() {
  return (
    <div >
      <Head>
        <title>Medicust</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <header
        style={{ backgroundImage: `url('https://i.ibb.co/rMmgLnM/hero.png')` }}
        className='w-full h-[90vh] bg-cover bg-center'>
        {/* <Image src={hero} alt="" /> */}
        <div className="container mx-auto flex justify-between items-center h-full">
          <div>
            <h2 className='text-2xl text-primary font-semibold'>Medical And Health</h2>
            <h1 className='text-6xl py-5   font-bold text-neutral'>
              A professional <br /> and friendly care <br /> provider.</h1>
            <p className='text-xl mt-2 mb-5'>Excepteur sint occaecat cupidatat non proident sunt officia</p>
            <button className='btn btn-primary px-10 mt-4 rounded-3xl'>All Doctors</button>
          </div>
        </div>
      </header>
      {/***************************** 
            seciton End Here 
      ****************************/}
      {/***************************** 
            seciton Start Here 
      ****************************/}
      <section className='py-14 container mx-auto'>
        <h1 className='text-4xl leading-tight font-bold text-neutral'>Need a doctor for checkup? <br />  Call for an emergency services!</h1>
      </section>

      {/***************************** 
            seciton End Here 
      ****************************/}
      {/***************************** 
            seciton Start Here 
      ****************************/}
      <Depertment />

      {/***************************** 
            seciton Start Here 
      ****************************/}
      <section className='container mx-auto my-10'>
        <div className='h-[500px] w-full bg-neutral relative rounded-md'>
          <div className=' left-48 right-52 absolute bottom-36 flex justify-center items-center bg-transparent'>
            <button className='bg-transparent animate-bounce'>
              <Image src={palyBtn} alt="" />
            </button>
          </div>
          <div className="w-[90%] mx-auto flex justify-between items-center h-full text-white">


            <div className='w-[50%]'>
              <h2 className='text-xl text-accent font-semibold'>Medical And Health</h2>
              <h1 className='text-5xl py-5   font-bold text-white'>
                A professional <br /> and friendly care <br /> provider.</h1>
              <p className='text-xl mt-2 mb-5'>Excepteur sint occaecat cupidatat non proident sunt officia</p>
              <button className='btn btn-primary px-10 mt-4 rounded-3xl'>All Doctors</button>
            </div>

            <div className='w-[50%]  h-full flex justify-end items-center'>
              <Image src={doctors} />
            </div>
          </div>
        </div>
      </section>

      {/***************************** 
            seciton End Here 
      ****************************/}
      {/***************************** 
            seciton Start Here 
      ****************************/}

      <section className='container mx-auto my-10'>
        
      </section>
    </div>
  )
}
